from dotenv import dotenv_values

env = dotenv_values(".env")

# queries

CHECKIFEXISTSBYID = env['CHECKIFEXISTSBYID']
CHECKIFEXISTSBYPHONE = env['CHECKIFEXISTSBYPHONE']
GETBYPHONE = env['GETBYPHONE']

CHECKIFEXISTSBYPAN = env['CHECKIFEXISTSBYPAN']
GETBYPAN = env['GETBYPAN']

CHECKIFEXISTSBYMAIL = env['CHECKIFEXISTSBYMAIL']
GETBYMAIL = env['GETBYMAIL']


CHECKIFUSEREXISTS = env['CHECKIFUSEREXISTS']
GETNAME = env['GETNAME']
GETADVISOR = env['GETADVISOR']
GETLOANDETAILS = env['GETLOANDETAILS']
GETEMIDETAILS = env['GETEMIDETAILS']
GETSTATUS = env['GETSTATUS']
GETMERCHANT = env['GETMERCHANT']
GETAPPLICANT = env['GETAPPLICANT']
GETSCORECARD = env['GETSCORECARD']
GETLENDER = env['GETLENDER']
GETDOCUMENTS = env['GETDOCUMENTS']
GETDIGIODETAILS = env['GETDIGIODETAILS']


CREATE_APPLICATION_ENTRY = env['CREATE_APPLICATION_ENTRY']
CREATE_USER_ENTRY = env['CREATE_USER_ENTRY']
CREATE_STATUS_LOG_ENTRY = env['CREATE_STATUS_LOG_ENTRY']
CREATE_ELEMENT_ENTRY = env['CREATE_ELEMENT_ENTRY']
INSERT_FILES = env['INSERT_FILES']
CHECK_FILE = env['CHECK_FILE']

UPDATE_APPLICATION = env['UPDATE_APPLICATION']

#Check duplicate rules

CHECKBYPAN = env['CHECKBYPAN']
CHECKBYPHONE = env['CHECKBYPHONE']
CHECKBYEMAIL = env['CHECKBYEMAIL']




